version: '3.8'
services:
  db:
    image: mysql
    environment:
      - MYSQL_DATABASE=rowdb
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - "./db/db_data:/var/lib/mysql"
      - "./scripts/db/01_create_tables.sql:/docker-entrypoint-initdb.d/01_create_tables.sql"
      - "./scripts/db/02_populate_test_types.sql:/docker-entrypoint-initdb.d/02_populate_test_types.sql"

  notebook:
    image: notebook
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - "./notebook/work:/nb"